<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/1a_Scalar_Vector_Matrix_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Tensor Rank | Prog/Math | Python
--- | --- | ----
0 | scalar | int, float, string, bool
1 | vector | list, tuple, set, dict, string, array, series
2 | matrix | nested list, matrix, data frame, list of lists, array of arrays, sheets, tables
3 | cube  | list of data frames, list of lists of lists, array of arrays of arrays
4 | tesseract  | list of lots



## Playing with Tensors

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
foo = np.arange(2**6)
foo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
foo.shape

(64,)

In [ ]:
foo.ndim

1

In [ ]:
foo.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
foo.reshape(1,-1).shape

(1, 64)

In [ ]:
foo.reshape(1,-1).ndim

2

In [ ]:
foo.reshape(1, 2,-1)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

In [ ]:
foo.reshape(1, 2,-1).shape # -1 Numpy does the work for you

(1, 2, 32)

In [ ]:
foo.reshape(1, -1, 2).shape

(1, 32, 2)

In [ ]:
foo.reshape(1, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [ ]:
foo.reshape(2, 2,-1)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

In [ ]:
foo.reshape(2, 2, -1).shape

(2, 2, 16)

In [ ]:
foo.reshape(2, 2, 2, -1)

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31]]],


       [[[32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47]],

        [[48, 49, 50, 51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60, 61, 62, 63]]]])

In [ ]:
foo.reshape(2, 2, 2, -1).shape

(2, 2, 2, 8)

In [ ]:
foo.reshape(2, 2, 2, 2, -1).shape

(2, 2, 2, 2, 4)

In [ ]:
foo.reshape(2, 2, 2, 2, 2, -1).shape

(2, 2, 2, 2, 2, 2)

In [ ]:
foo.reshape(2, 2, 2, 2, 2, 2, -1).shape, foo.reshape(2, 2, 2, 2, 2, 2, -1).ndim

((2, 2, 2, 2, 2, 2, 1), 7)

In [ ]:
foo.reshape(1, 2, 2, 2, 2, 2, 2, -1).shape

(1, 2, 2, 2, 2, 2, 2, 1)

In [ ]:
foo.reshape(1, 2, 2, 2, 2, 2, 2, -1).size

64

In [ ]:
len(foo.reshape(1, 1, 2, 2, 2, 2, 2, 2, -1).shape)

9

In [ ]:
foo.reshape(1, 1, 2, 2, 2, 2, 2, 2, -1).ndim

9

In [ ]:
foo.reshape(1, 1, 2, 2, 2, 2, 2, 2, -1).size

64

In [ ]:
foo.reshape(1, 64).shape

(1, 64)

In [ ]:
foo.reshape(1, 1, 64).shape

(1, 1, 64)

In [ ]:
foo.reshape(1, -1, 2).flatten().shape

(64,)

In [ ]:
foo.reshape(1, -1, 2).reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
foo.reshape(1, 65).shape

ValueError: cannot reshape array of size 64 into shape (1,65)

In [ ]:
foo.reshape(2, -1, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]],


       [[[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51]],

        [[52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59]],

        [[60, 61],
         [62, 63]]]])

## Maximum dimensions


### Numpy

In [ ]:
# 65 doesn't work
n = 64
shape = [1] * n
f"{np.array([1]).reshape(shape).ndim:,.0f}"

'64'

In [ ]:
np.array([1]).reshape(shape)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

### TensorFlow

In [ ]:
# 254 doesn't work
n = 253
shape = (1,) * n
tf.rank(tf.reshape([1], shape))

<tf.Tensor: shape=(), dtype=int32, numpy=253>

### PyTorch


In [ ]:
# 242 MM crashes, RAM seems to be limitation
n = 241_000_000
shape = (1,) * n
f"{torch.tensor([1]).reshape(shape).ndim:,.0f}"

'241,000,000'